apiVersion: v1
kind: BuildConfig
metadata:
  name: statspipeline
  labels:
    name: statspipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "stats", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') {\nstage 'buildInDevelopment'\nopenshiftBuild(namespace: 'jboss', buildConfig: 'stats', showBuildLogs: 'true')\nstage 'deployInDevelopment'\nopenshiftDeploy(namespace: 'jboss', deploymentConfig: 'stats')\nopenshiftScale(namespace: 'jboss', deploymentConfig: 'stats',replicaCount: '1')\n}"
  output:
  resources:
  postCommit:
status:
  lastVersion: 1

