apiVersion: v1
kind: BuildConfig
metadata:
  name: myfirstpipeline
  labels:
    name: myfirstpipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "s2i-quickstart-cdi-camel", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') {\nstage 'buildInDevelopment'\nopenshiftBuild(namespace: 'development', buildConfig: 's2i-quickstart-cdi-camel', showBuildLogs: 'true')\nstage 'deployInDevelopment'\nopenshiftDeploy(namespace: 'development', deploymentConfig: 's2i-quickstart-cdi-camel')\nopenshiftScale(namespace: 'development', deploymentConfig: 's2i-quickstart-cdi-camel',replicaCount: '1')\nstage 'deployInTesting'\nopenshiftTag(namespace: 'development', sourceStream: 's2i-quickstart-cdi-camel',  sourceTag: 'latest', destinationStream: 's2i-quickstart-cdi-camel', destinationTag: 'promoteToQA')\nopenshiftDeploy(namespace: 'testing', deploymentConfig: 's2i-quickstart-cdi-camel')\nopenshiftScale(namespace: 'testing', deploymentConfig: 's2i-quickstart-cdi-camel',replicaCount: '1')\n}"
  output:
  resources:
  postCommit:
status:
  lastVersion: 1

