//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.07 at 10:08:16 AM GMT 
//


package com.redhat.ukiservices.model.jaxb.ref;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="code" use="required" type="{http://www.thalesgroup.com/rtti/XmlRefData/v3}ReasonCodeType" /&gt;
 *       &lt;attribute name="reasontext" use="required" type="{http://www.thalesgroup.com/rtti/XmlRefData/v3}ReasonTextType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Reason")
public class Reason {

    @XmlAttribute(name = "code", required = true)
    protected int code;
    @XmlAttribute(name = "reasontext", required = true)
    protected String reasontext;

    /**
     * Gets the value of the code property.
     * 
     */
    public int getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     */
    public void setCode(int value) {
        this.code = value;
    }

    /**
     * Gets the value of the reasontext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasontext() {
        return reasontext;
    }

    /**
     * Sets the value of the reasontext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasontext(String value) {
        this.reasontext = value;
    }

}
