apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: unified-jboss-ocp
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: etl
      delete: appdev
    name: etl
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: etl:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/benemon/unified-jboss-ocp
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_ARGS_APPEND
          value: -pl etl --also-make
        - name: ARTIFACT_DIR
          value: etl/target/
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:1.0
          namespace: openshift
      type: Source
    triggers:
    - generic:
        secret: 5f36d4a0fb372c81
      type: Generic
    - github:
        secret: 9aa0a9fe3f71cc11
      type: GitHub
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: ingest
      delete: appdev
    name: ingest
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ingest:latest
        namespace: appdev
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/benemon/unified-jboss-ocp
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_ARGS_APPEND
          value: -pl ingest --also-make
        - name: ARTIFACT_DIR
          value: ingest/target
        - name: MODULE_DIR
          value: ingest
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:1.0
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: e1389910db65e33f
      type: GitHub
    - generic:
        secret: 0d01fb39280420ab
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: ref
      delete: appdev
    name: ref
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ref:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/benemon/unified-jboss-ocp
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_ARGS_APPEND
          value: -pl refdataloader --also-make
        - name: ARTIFACT_DIR
          value: refdataloader/target/
        - name: MODULE_DIR
          value: refdataloader/
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:1.0
          namespace: openshift
      type: Source
    triggers:
    - generic:
        secret: 9c048ba01c1ab7b6
      type: Generic
    - github:
        secret: ad9465d50d59ff32
      type: GitHub
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: stats
      delete: appdev
    name: stats
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: stats:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/benemon/unified-jboss-ocp
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_ARGS_APPEND
          value: -pl jdgstats --also-make
        - name: ARTIFACT_DIR
          value: jdgstats/target/
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:1.0
          namespace: openshift
      type: Source
    triggers:
    - generic:
        secret: 43383b038199c1d7
      type: Generic
    - github:
        secret: 8310183cac7c5b35
      type: GitHub
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: etl
      delete: appdev
    name: etl
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.248.101:5000/appdev/etl:latest
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: ingest
      delete: appdev
    name: ingest
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.248.101:5000/appdev/ingest:latest
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: ref
      delete: appdev
    name: ref
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.248.101:5000/appdev/ref:latest
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: stats
      delete: appdev
    name: stats
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.248.101:5000/appdev/stats:latest
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 2
    labels:
      app: amq62-basic
      application: broker
      delete: amq
      template: amq62-basic
      xpaas: 1.3.1
    name: broker-amq
  spec:
    replicas: 1
    selector:
      deploymentConfig: broker-amq
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 0
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          application: broker
          deploymentConfig: broker-amq
        name: broker-amq
      spec:
        containers:
        - env:
          - name: AMQ_USER
            value: redhat
          - name: AMQ_PASSWORD
            value: redhat
          - name: AMQ_TRANSPORTS
            value: openwire
          - name: AMQ_QUEUES
          - name: AMQ_TOPICS
          - name: MQ_SERIALIZABLE_PACKAGES
          - name: AMQ_MESH_DISCOVERY_TYPE
            value: kube
          - name: AMQ_MESH_SERVICE_NAME
            value: broker-amq-tcp
          - name: AMQ_MESH_SERVICE_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: AMQ_STORAGE_USAGE_LIMIT
            value: 1 gb
          image: registry.access.redhat.com/jboss-amq-6/amq62-openshift@sha256:acadeae82790e144cc8631db9a78344cad2b359bc46d463a556c77caf08b11be
          imagePullPolicy: Always
          name: broker-amq
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 5672
            name: amqp
            protocol: TCP
          - containerPort: 1883
            name: mqtt
            protocol: TCP
          - containerPort: 61613
            name: stomp
            protocol: TCP
          - containerPort: 61616
            name: tcp
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/amq/bin/readinessProbe.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 60
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - broker-amq
        from:
          kind: ImageStreamTag
          name: jboss-amq-62:1.3
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 1
    observedGeneration: 2
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 2
    labels:
      app: datagrid65-basic
      application: datagrid-app
      delete: jdg
      template: datagrid65-basic
      xpaas: 1.2.0
    name: datagrid-app
  spec:
    replicas: 1
    selector:
      deploymentConfig: datagrid-app
    strategy:
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          application: datagrid-app
          deploymentConfig: datagrid-app
        name: datagrid-app
      spec:
        containers:
        - env:
          - name: USERNAME
            value: redhat
          - name: PASSWORD
            value: S3cur1ty!
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=datagrid-app
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INFINISPAN_CONNECTORS
            value: hotrod,rest
          - name: CACHE_NAMES
            value: ref,darwindata
          - name: ENCRYPTION_REQUIRE_SSL_CLIENT_AUTH
          - name: HOTROD_SERVICE_NAME
            value: datagrid-app-hotrod
          - name: MEMCACHED_CACHE
          - name: REST_SECURITY_DOMAIN
          - name: JGROUPS_CLUSTER_PASSWORD
            value: iarw6keV
          image: registry.access.redhat.com/jboss-datagrid-6/datagrid65-openshift@sha256:c3800b3cbdc7b6c61d9e0c1810f035e601d58f93292587afb5152ebd6d05ffbe
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/datagrid/bin/livenessProbe.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: datagrid-app
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          - containerPort: 11211
            name: memcached
            protocol: TCP
          - containerPort: 11222
            name: hotrod
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/datagrid/bin/readinessProbe.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 60
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - datagrid-app
        from:
          kind: ImageStreamTag
          name: jboss-datagrid65-openshift:1.2
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 1
    observedGeneration: 2
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 5
    labels:
      app: etl
      delete: appdev
    name: etl
  spec:
    replicas: 1
    selector:
      deploymentconfig: etl
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: etl
          delete: appdev
          deploymentconfig: etl
      spec:
        containers:
        - env:
          - name: DARWIN_CACHE_NAME
            value: darwindata
          - name: REF_DATA_CACHE_NAME
            value: ref
          - name: BROKER_AMQ_TCP_USERNAME
            value: redhat
          - name: BROKER_AMQ_TCP_PASSWORD
            value: redhat
          image: 172.30.248.101:5000/appdev/etl@sha256:7f70f72fea005f4ff96dab26ddf1e716f7054e0cf4da8e96585ba07b4dd9e6d7
          imagePullPolicy: Always
          name: etl
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - etl
        from:
          kind: ImageStreamTag
          name: etl:latest
          namespace: appdev
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 1
    observedGeneration: 5
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 5
    labels:
      app: ingest
      delete: appdev
    name: ingest
  spec:
    replicas: 1
    selector:
      deploymentconfig: ingest
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ingest
          delete: appdev
          deploymentconfig: ingest
      spec:
        containers:
        - env:
          - name: BROKER_AMQ_TCP_USERNAME
            value: redhat
          - name: BROKER_AMQ_TCP_PASSWORD
            value: redhat
          image: 172.30.248.101:5000/appdev/ingest@sha256:f33259dd43b4aa504b372c6f4cc39e33acf0282a6b0d8577f3e42c265e71b781
          imagePullPolicy: Always
          name: ingest
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 384Mi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ingest
        from:
          kind: ImageStreamTag
          name: ingest:latest
          namespace: appdev
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 1
    observedGeneration: 5
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 9
    labels:
      app: ref
      delete: appdev
    name: ref
  spec:
    replicas: 1
    selector:
      deploymentconfig: ref
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ref
          delete: appdev
          deploymentconfig: ref
      spec:
        containers:
        - env:
          - name: REFERENCE_DATA_DIRECTORY
            value: /deployments/ref
          image: 172.30.248.101:5000/appdev/ref@sha256:44e5ddc20829dcd3ef899fc2dd193207e38d4c95d34787d609024d13bbf22532
          imagePullPolicy: Always
          name: ref
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 384Mi
            requests:
              cpu: 250m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ref
        from:
          kind: ImageStreamTag
          name: ref:latest
          namespace: appdev
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 1
    observedGeneration: 9
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 3
    labels:
      app: stats
      delete: appdev
    name: stats
  spec:
    replicas: 1
    selector:
      deploymentconfig: stats
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: stats
          delete: appdev
          deploymentconfig: stats
      spec:
        containers:
        - env:
          - name: DARWIN_CACHE_NAME
            value: darwindata
          - name: REF_DATA_CACHE_NAME
            value: ref
          image: 172.30.248.101:5000/appdev/stats@sha256:eb850996d88813722542acfacc7e3869f08ea5ae4ff9606a32427d41434d7971
          imagePullPolicy: Always
          name: stats
          ports:
          - containerPort: 8778
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 384Mi
            requests:
              cpu: 250m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - stats
        from:
          kind: ImageStreamTag
          name: stats:latest
          namespace: appdev
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 1
    observedGeneration: 3
    replicas: 1
    updatedReplicas: 1