//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.01 at 05:45:00 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.thalesgroup.com/rtti/PushPort/Forecasts/v2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.redhat.ukiservices.etl.model;
