//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.02 at 02:34:25 PM GMT 
//


package com.redhat.ukiservices.etl.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Platform number with associated flags
 * 
 * <p>Java class for PlatformData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlatformData"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1&gt;PlatformType"&gt;
 *       &lt;attribute name="platsup" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="cisPlatsup" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="platsrc" default="P"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;length value="1"/&gt;
 *             &lt;enumeration value="P"/&gt;
 *             &lt;enumeration value="A"/&gt;
 *             &lt;enumeration value="M"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="conf" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlatformData", namespace = "http://www.thalesgroup.com/rtti/PushPort/Forecasts/v2", propOrder = {
    "value"
})
public class PlatformData {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "platsup")
    protected Boolean platsup;
    @XmlAttribute(name = "cisPlatsup")
    protected Boolean cisPlatsup;
    @XmlAttribute(name = "platsrc")
    protected String platsrc;
    @XmlAttribute(name = "conf")
    protected Boolean conf;

    /**
     * Defines a platform number
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the platsup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPlatsup() {
        if (platsup == null) {
            return false;
        } else {
            return platsup;
        }
    }

    /**
     * Sets the value of the platsup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlatsup(Boolean value) {
        this.platsup = value;
    }

    /**
     * Gets the value of the cisPlatsup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCisPlatsup() {
        if (cisPlatsup == null) {
            return false;
        } else {
            return cisPlatsup;
        }
    }

    /**
     * Sets the value of the cisPlatsup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCisPlatsup(Boolean value) {
        this.cisPlatsup = value;
    }

    /**
     * Gets the value of the platsrc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatsrc() {
        if (platsrc == null) {
            return "P";
        } else {
            return platsrc;
        }
    }

    /**
     * Sets the value of the platsrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatsrc(String value) {
        this.platsrc = value;
    }

    /**
     * Gets the value of the conf property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isConf() {
        if (conf == null) {
            return false;
        } else {
            return conf;
        }
    }

    /**
     * Sets the value of the conf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConf(Boolean value) {
        this.conf = value;
    }

}
