//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.02 at 02:34:25 PM GMT 
//


package com.redhat.ukiservices.etl.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Type describing each type of alarm that can be set.
 * 
 * <p>Java class for RTTIAlarmData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTTIAlarmData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="tdAreaFail" type="{http://www.thalesgroup.com/rtti/PushPort/CommonTypes/v1}TDAreaIDType"/&gt;
 *         &lt;element name="tdFeedFail" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="tyrellFeedFail" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.thalesgroup.com/rtti/PushPort/Alarms/v1}AlarmID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTTIAlarmData", namespace = "http://www.thalesgroup.com/rtti/PushPort/Alarms/v1", propOrder = {
    "tdAreaFail",
    "tdFeedFail",
    "tyrellFeedFail"
})
public class RTTIAlarmData {

    protected String tdAreaFail;
    protected Object tdFeedFail;
    protected Object tyrellFeedFail;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the tdAreaFail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTdAreaFail() {
        return tdAreaFail;
    }

    /**
     * Sets the value of the tdAreaFail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTdAreaFail(String value) {
        this.tdAreaFail = value;
    }

    /**
     * Gets the value of the tdFeedFail property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTdFeedFail() {
        return tdFeedFail;
    }

    /**
     * Sets the value of the tdFeedFail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTdFeedFail(Object value) {
        this.tdFeedFail = value;
    }

    /**
     * Gets the value of the tyrellFeedFail property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTyrellFeedFail() {
        return tyrellFeedFail;
    }

    /**
     * Sets the value of the tyrellFeedFail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTyrellFeedFail(Object value) {
        this.tyrellFeedFail = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
